### ISSUE TITLE
Typeerror from generated js code

### ISSUE THREAD

**Issue by jamesdesmond** [open-telemetry/opentelemetry-proto#380]
First, apologies if this is the wrong repo to file this issue.
I am running a gRPC OpenTelemetry server on port 9090 that works with both the Python and Java OpenTelemetry libraries from PyPi / Maven.
I cloned the repo, and ran `make gen-js`.
I then added these .js files to my Node project.
I invoke a LogsServiceClient:
```
const { LogsServiceClient } = require("./opentelemetry/proto/collector/logs/v1/logs_service_grpc_web_pb.js");
const client = new LogsServiceClient("http://localhost:9090", grpc.credentials.createInsecure());
const formData =  { ... } //a dict full of data to be marshalled into ExportLogsServiceRequest
global.XMLHttpRequest = require('xhr2'); //https://github.com/grpc/grpc-web/issues/453

function export_foo(formData) {
   ...60 lines of building up an ExportLogsServiceRequest....
    const my_exportlogsservicerequest = new ExportLogsServiceRequest;
    my_exportlogsservicerequest.addResourceLogs(my_resource_logs);
    client.export(my_exportlogsservicerequest);
}
function main() {
    export_foo(formData);
};

main();
```

I get the following output in the console:
```
TypeError: b is not a function
    at Array.<anonymous> (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/grpc-web/index.js:66:121)
    at Y (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/grpc-web/index.js:58:358)
    at qc.<anonymous> (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/grpc-web/index.js:57:87)
    at Jb (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/grpc-web/index.js:35:182)
    at O (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/grpc-web/index.js:34:615)
    at yc (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/grpc-web/index.js:45:411)
    at Ac (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/grpc-web/index.js:48:228)
    at qc.n.W (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/grpc-web/index.js:46:252)
    at qc.n.R (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/grpc-web/index.js:46:231)
    at XMLHttpRequest.dispatchEvent (/Users/n1561730/workspace/ServiceRecorder-node/node_modules/xhr2/lib/xhr2.js:76:20)
```
My package.json deps are as follows:
```
    "@grpc/grpc-js": "^1.5.10",
    "body-parser": "^1.19.2",
    "express": "^4.17.3",
    "fs": "^0.0.1-security",
    "google-protobuf": "^3.20.0-rc.2",
    "grpc-web": "^1.3.1",
    "nano-time": "^1.0.0",
    "uuid": "^8.3.2",
    "xhr2": "^0.2.1"
```

I know that js is not listed in the README.md as supported, apologies if the answer is as simple as "JS doesn't work with opentelemetry-proto".

If there is a repo where I may get support on this issue please let me know so I can file the ticket there.

**Comment by tigrannajaryan** [comment]
Moving to JS repo since this appears to be a strictly JS issue.
